--
-- Table "EBA_DEMO_CAL_MYSESSIONS"
--
CREATE TABLE "APPTESTEXAMPLE"."EBA_DEMO_CAL_MYSESSIONS" 
   (	"ID" NUMBER, 
	"ROW_VERSION_NUMBER" NUMBER, 
	"TITLE" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SESSION_TYPE" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SPEAKER" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"START_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE NOT NULL ENABLE, 
	"STATUS" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "EBA_DEMO_CAL_MYEVENTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/