--
-- Table "EBA_DEMO_CAL_PROJECTS"
--
CREATE TABLE "APPTESTEXAMPLE"."EBA_DEMO_CAL_PROJECTS" 
   (	"ID" NUMBER, 
	"ROW_VERSION_NUMBER" NUMBER, 
	"PROJECT" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"TASK_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"START_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE NOT NULL ENABLE, 
	"STATUS" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"ASSIGNED_TO" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"COST" NUMBER, 
	"BUDGET" NUMBER, 
	 CONSTRAINT "EBA_DEMO_CAL_PROJECTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/