--
-- Table "EBA_DEMO_APPR_LAPTOP_STOCK"
--
CREATE TABLE "APPTESTEXAMPLE"."EBA_DEMO_APPR_LAPTOP_STOCK" 
   (	"LAPTOP_TYPE" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"AMOUNT" NUMBER, 
	 CONSTRAINT "EBA_DEMO_APPR_LAPTOP_STOCK_LAPTOP_TYPE_PK" PRIMARY KEY ("LAPTOP_TYPE")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/