name: Deploy to Oracle ADB

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TNS_ADMIN: ${{ runner.temp }}/wallet
      DB_ALIAS: demodevopsapex
      DB_USER: SABATH.GARCIA
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SQLcl
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget https://download.oracle.com/sqlcl/sqlcl-latest.zip -O sqlcl.zip
        unzip -q sqlcl.zip -d ${{ runner.tool_cache }}/sqlcl
      shell: bash

    - name: Download and unzip Wallet
      run: |
        mkdir -p "${{ env.TNS_ADMIN }}"
        unzip -o wallet.zip -d "${{ env.TNS_ADMIN }}"
      shell: bash

    - name: Run SQL script on Oracle ADB
      run: |
        export PATH=${{ runner.tool_cache }}/sqlcl/sqlcl/bin:$PATH
        echo exit | sql -s "${DB_USER}/${DB_PASSWORD}@${DB_ALIAS}" @EMPLOYEES.sql
      shell: bash
