name: Deploy to Oracle ADB

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TNS_ADMIN: ${{ github.workspace }}/wallet
      DB_ALIAS: demodevopsapex
      DB_USER: SABATH.GARCIA
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SQLCL_DIR: ${{ github.workspace }}/sqlcl

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SQLcl
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget --no-cookies --no-check-certificate \
             --header "Cookie: oraclelicense=accept-securebackup-cookie" \
             https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip -O sqlcl.zip
        unzip -q sqlcl.zip -d sqlcl
      shell: bash  

    - name: Download and unzip Wallet
      run: |
        mkdir -p "${TNS_ADMIN}"
        unzip -o wallet.zip -d "${TNS_ADMIN}"
      shell: bash

    - name: Run SQL script on Oracle ADB
      run: |
        export PATH=${SQLCL_DIR}/sqlcl/bin:$PATH
        echo exit | sql -s ${DB_USER}/${DB_PASSWORD}@${DB_ALIAS} @EMPLOYEES.sql
      shell: bash
